### ISSUE TITLE
nvim windows ls not working

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [Equilibris/nx.nvim#10]
I guess that is solely a windows problem. may also be related to #8 

being in the nx.json and trying to do
`lua require('nx.read-configs').scandir('./')`
results in
`'ls' is not recognized as an internal or external command`

**Comment by technbuzz** [comment]
Same here on windows experiencing this and many problems looks like need to get into plugin development

**Comment by Equilibris** [comment]
hi could you try to re-run it? it should be fixed now

**Comment by Equilibris** [comment]
I'm closing for now, will open it up if the error occurs again

**Comment by Equilibris** [comment]
I'm closing for now, will open it up if the error occurs again

**Comment by Equilibris** [comment]
I'm closing for now, will open it up if the error occurs again
