### ISSUE TITLE
Sometime getting unmodified buffer error

### ISSUE THREAD

**Issue by technbuzz** [Equilibris/nx.nvim#16]
**Describe the bug**
Occasionally I am getting following error when I create Angular library or generate component

**To Reproduce**
1. Go to ':Telescope nx generators'
2. Search for Angular Component
3. Provide all the required field
4. Click Submit
5. Get following error (as shown in screenshot)

**Expected behavior**

**Screenshots**
<img width="1177" alt="Screenshot 2023-07-28 at 3 37 35 PM" src="https://github.com/Equilibris/nx.nvim/assets/1523391/7016d47e-76b2-4a26-8453-3494f9634cdf">

**Desktop (please complete the following information):**
 - OS: Mac
 - Nvim: 0.9.0

**Comment by Equilibris** [comment]
Hi, I am a bit unsure how to replicate this. Could you link me your config?

**Comment by Equilibris** [comment]
Ive added a lot of logging to the plugin now, could you navigate to `.local/share/nvim` and delete the file called `nx.log`, then re open nvim, call `Telescope nx generators`, then upload the `nx.log` file here
