### ISSUE TITLE
Generators should read nx.json

### ISSUE THREAD

**Issue by technbuzz** [Equilibris/nx.nvim#17]
**Is your feature request related to a problem? Please describe.**
Whenever I try to create a library, I want certain feature to be selected. In nx.json file we can set default values to a particular library. For now it's repetitive to set certain options. i

**Describe the solution you'd like**
For instance we can set the library to be `buildable` and this option we be automatically set to true when using the generators.

**Describe alternatives you've considered**
I already have how effective it is in the NX plugin of VSCode.

**Comment by Equilibris** [comment]
Ah yes, this should be relatively easy to implement, I will quickly try now, but I'll get back to you whether it becomes a greater challenge

**Comment by Equilibris** [comment]
It should now be implemented, please confirm that it works as expected then close the issue if satasfied

**Comment by technbuzz** [comment]
I am trying to update this plugin but getting this error
<img width="882" alt="Screenshot 2023-08-02 at 2 37 06 PM" src="https://github.com/Equilibris/nx.nvim/assets/1523391/837de928-bc3b-4f2c-8f0c-0e8b5e476952">

**Comment by Equilibris** [comment]
please uninstall the plugin, then reinstall it. It looks like something has modified its doc/tags

**Comment by technbuzz** [comment]
Yeah Uninstalling helped, But the `nx.json` isn't got read. Here is some config for angular libraries and components
 
<img width="384" alt="image" src="https://github.com/Equilibris/nx.nvim/assets/1523391/79a7ee62-c2ff-4329-b3a2-097172f3d1f7">

and that's how generator looks in nvim

<img width="1176" alt="image" src="https://github.com/Equilibris/nx.nvim/assets/1523391/63d79c84-972c-425f-86f5-eaa9ceab5130">

**Comment by Equilibris** [comment]
can you send me the log?

And ill fix this just after breakfast

**Comment by technbuzz** [comment]
[nx.log](https://github.com/Equilibris/nx.nvim/files/12239595/nx.log)

I have attached the log file.

**Comment by Equilibris** [comment]
It was such a dumb mistake on my side, please try again, it should be fixed

**Comment by technbuzz** [comment]
Yeah it works, thanks
