### ISSUE TITLE
nx generators list empty

### ISSUE THREAD

**Issue by technbuzz** [Equilibris/nx.nvim#8]
I managed to create a library for the first time. But when I tried to create to open the generators window in telescope by typing
`:Telescope nx generators`

An empty telescope windows showed up?

**Comment by Equilibris** [comment]
Hi could you run the command `:lua require('nx.read-configs').read_nx_root()` and send the output of `:lua require('nx.utils').pd(_G.nx)`

**Comment by sschneider-ihre-pvs** [comment]
`:lua require('nx.read-configs').read_nx_root()`
```
E5108: Error executing lua ...m\site\pack\packer\start\nx.nvim/lua\nx\read-configs.lua:36: attempt to index field 'nx' (a nil value)
stack traceback:
        ...m\site\pack\packer\start\nx.nvim/lua\nx\read-configs.lua:36: in function 'read_nx'
        ...m\site\pack\packer\start\nx.nvim/lua\nx\read-configs.lua:119: in function 'read_nx_root'
        [string ":lua"]:1: in main chunk
```

`:lua require('nx.utils').pd(_G.nx)`
```
nil
```

**Comment by Equilibris** [comment]
Hi
