### ISSUE TITLE
workspace.json is deprecated

### ISSUE THREAD

**Issue by quinnromanek** [Equilibris/nx.nvim#9]
**Describe the bug**
In the current version of nx, [workspace.json has been deprecated](https://nx.dev/deprecated/workspace-json).  Projects are now indicated by the presence of a package.json or project.json and run targets can be defined in package.json.

A possible alternative ([from this discussion](https://github.com/nrwl/nx/issues/7472) )is a combination of running `nx affected:libs --all --plain` and `nx affected:apps --all --plain` to load all projects, since it's possible to install arbitrary plugins for project inference.

**To Reproduce**
* Do [package-based repo tutorial](https://nx.dev/getting-started/package-based-repo-tutorial) from nx.dev
* Open nvim and open action finder
* Observe that no actions have been populated

**Expected behavior**
Actions from project's package.json scripts section have been populated in the telescope picker.

**Desktop (please complete the following information):**
 - OS: MacOS Iterm2
 - NVIM 8.1

**Comment by Equilibris** [comment]
Cool thanks I will patch this in over the next week.

**Comment by quinnromanek** [comment]
Awesome! The command I sent probably won't actually work since it doesn't include filepaths - I looked at the VS code extension and it seems like they [read the project graph](https://github.com/nrwl/nx-console/blob/master/libs/language-server/workspace/src/lib/get-nx-workspace-config.ts) for this purpose. So I guess just using `nx graph --file` and parsing the graph would be the most robust solution.

I have some local copy close to working, I'll send a PR if I can figure it out

**Comment by SteffenLm** [comment]
Hey there,
is there any update on this? Can i support somehow?

**Comment by ceuk** [comment]
Hey all, I've got a hacky temp fix for actions on [my fork](https://github.com/ceuk/nx.nvim). Generators still won't work I don't think but it would also be a fairly simple fix in line with what I've done for actions

**Comment by rodrigc** [comment]
It’s best to mimic the logic in https://github.com/nrwl/nx-console

**Comment by Equilibris** [comment]
yeah after a long break its fixed. sorry everyone

**Comment by rodrigc** [comment]
@Equilibris NX keeps changing their stuff around, breaking external stuff.
Appreciate your efforts to bring this back.

**Comment by Equilibris** [comment]
Yeah thanks, it took quite the effort, but at least it'll be easier next time

**Comment by rodrigc** [comment]
Until NX breaks again everything 🤣

**Comment by Equilibris** [comment]
hahaha, yeah true, ill sure be faster then, this was way too slow haha
